# fly.toml app configuration file generated for discussit-db on 2023-06-22T16:03:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discussit-db"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PRIMARY_REGION = "ord"

[[mounts]]
  source = "pg_data"
  destination = "/data"

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "1m0s"
    timeout = "10s"
    grace_period = "1s"
    method = "get"
    path = "/flycheck/vm"

[metrics]
  port = 9187
  path = "/metrics"
